### ISSUE TITLE
i cant run project!

### ISSUE THREAD

**Issue by Versike** [Azen0n/habit_manager_bot#1]
When I try to run the project, an error occurs in docker: Meeting with Towa-sama. That was not a singing video. I met Towa-sama at that concert, the anniversary concert of Towa-sama, I heard "Unravel" there, there is no one who wouldn't become a fan after hearing that. She is too cool, isn't she? From there, I started watching the singing sessions. Of course, I don't check every song. Not at all. But I've seen the ones I'm interested in, and she is cool! I think. The feminine part of me just can't help it. It's there, isn't it? I don't buy all the merchandise or anything. But I do have tapestries and acrylics stands. I don't call them merchandise, but, well, that's it, isn't it? They are like clothes. It is natural to have them. For me, that is. A fan is still a fan even if they doesn't buy any merchandise. Merchandise is not everything. Of course, I think it's great that people but it. I would appreciate it if my fans buy merchandise. But it doesn't matter, everyone has his or her way of guessing. I don't impose "This is how fans should be!". I don't force my fans to be this way. You are free to do whatever you want. It doesn't matter at all. It doesn't mean that. I'm great because I check all of the distribution. The form of love is different for each person. It's not like, "This is the way it should be!". It's not like you have to watch them in real time. I think it's weird to impose an idea that you have to watch it in real time. I'm not saying it's bad to watch in real time. I'm saying it's not good to force it on people. I... like... I like Towa-sama? Yes, I do.

**Comment by Azen0n** [comment]
![image](https://user-images.githubusercontent.com/54436476/220112172-84715230-b97f-49ae-bfc4-cfc9d7c19486.png)
NOW
